name: cs_mobile
description: A platform to make sharing information easier.

publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  firebase_core: ^1.22.0
  firebase_auth: ^3.3.11
  flutter_riverpod: ^1.0.3
  github_sign_in: ^0.0.5-dev.4
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  animations: ^2.0.2
  flutter_markdown: ^0.6.10
  like_button: ^2.0.4
  dynamic_color: ^1.5.3
  timeago: ^3.3.0
  go_router: ^6.0.1
  share_plus: ^4.1.0
  url_launcher: ^6.1.5
  flutter_math_fork: ^0.6.3+1
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  in_app_update: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_quill: ^6.0.6+1
  flutter_quill_extensions: ^0.1.0
  delta_markdown: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

