name: cs_mobile
description: A platform to make sharing information easier.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  string_validators:
    git:
      url: https://github.com/bizz84/codewithandrea_flutter_packages
      path: packages/string_validators
  alert_dialogs:
    git:
      url: https://github.com/bizz84/codewithandrea_flutter_packages
      path: packages/alert_dialogs
  http: ^0.13.4
  firebase_core: ^1.22.0
  firebase_auth: ^3.3.11
  flutter_riverpod: ^1.0.3
  github_sign_in: ^0.0.5-dev.4
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  awesome_icons: ^1.1.0
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  animations: ^2.0.2
  flutter_markdown: ^0.6.10
  like_button: ^2.0.4
  image_picker: ^0.8.5
  text_selection_controls: 
    git:
      url: https://github.com/YoussefLasheen/flutter_text_selection_controls
      path: text_selection_controls/
  dynamic_color: ^1.5.3
  timeago: ^3.3.0
  go_router: ^4.4.1
  share_plus: ^4.1.0
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true